Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,9 +39,15 @@ jobs:
       - name: Disable Code Signing for Simulator
         run: |
           cd ios
-          # Disable automatic signing for the simulator
-          sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = /g' ios/Runner.xcodeproj/project.pbxproj
-          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = /g' ios/Runner.xcodeproj/project.pbxproj
+          # Ensure the path is correct before trying to disable code signing
+          if [ -f "Runner.xcodeproj/project.pbxproj" ]; then
+            # Disable automatic signing for the simulator
+            sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = /g' Runner.xcodeproj/project.pbxproj
+            sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = /g' Runner.xcodeproj/project.pbxproj
+          else
+            echo "Runner.xcodeproj/project.pbxproj not found!"
+            exit 1
+          fi
 
       - name: Get Available Simulator Name
         run: |
